#ifndef dataStructures_h
#define dataStructures_h

#include <vector>
#include <opencv2/core.hpp>


struct DataFrame { // represents the available sensor information at the same time instance
    
    cv::Mat cameraImg; // camera image
    
    std::vector<cv::KeyPoint> keypoints; // 2D keypoints within camera image
    cv::Mat descriptors; // keypoint descriptors
    std::vector<cv::DMatch> kptMatches; // keypoint matches between previous and current frame
    /*
    DataFrame(const DataFrame& d)
    {
        *this=d;        
        std::cout << "DataFrame generated by copy constructor." << std::endl;
    }
    DataFrame()
    {
        std::cout << "DataFrame generated." << std::endl;
    }
    ~DataFrame()
    {
        std::cout << "DataFrame deleted." << std::endl;
    }
    */
};


#endif /* dataStructures_h */
